name: flutter_manifest
description: Flutter package to manage Web App manifest. Supports generating the manifest
  file and reading information from manifest.json in assets.
version: 0.1.2
homepage: https://github.com/jtn-d/flutter_manifest.git

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^2.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_manifest:
  orientation: "portrait"
  theme_color: "#F00"
  background_color: "#000"